name: Build and Release
on:
  push:
    paths-ignore:
      - 'packages/docs/**'
      - 'README.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm i
      - name: Lint
        run: pnpm -r run lint

      - name: Test
        run: pnpm -r test
      - name: Upload code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: ${{github.workspace}}/packages/core/coverage/lcov.info:lcov
          prefix: test
      - name: Build
        run: pnpm -r run build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: github.ref_name == 'main'
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version # pnpm changeset version && pnpm install --lockfile-only
          publish: pnpm run ci:publish
          commit: 'chore: update versions'
          title: 'Release: new versions'
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
