name: Publish Docs
on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.ref == 'refs/heads/main' || github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
        working-directory: 'docs'
      - name: Generate Documentation
        run: npm run docs:build
        working-directory: 'docs'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
