name: Publish Docs
on:
  push:
    branches:
      - main

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i
      - name: Generate Documentation
        run: pnpm --filter=docs run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/.vitepress/dist
